package org.terraform.structure;

import org.jetbrains.annotations.NotNull;
import org.terraform.biome.BiomeBank;
import org.terraform.coregen.populatordata.PopulatorDataAbstract;
import org.terraform.data.TerraformWorld;
import java.util.Random;

public class GenericVanillaStructurePopulator extends VanillaStructurePopulator {
    private final boolean enabled;
    private final int seedModifier;
    private final BiomeBank[] allowedBiomes;

    public GenericVanillaStructurePopulator(String structureKey, boolean enabled, int seedModifier, BiomeBank... allowedBiomes) {
        super(structureKey);
        this.enabled = enabled;
        this.seedModifier = seedModifier;
        this.allowedBiomes = allowedBiomes;
    }

    @Override
    public boolean canSpawn(@NotNull TerraformWorld tw, int chunkX, int chunkZ, BiomeBank biome) {
        if (!isEnabled()) return false;
        if (allowedBiomes.length > 0) {
            boolean biomeAllowed = false;
            for (BiomeBank b : allowedBiomes) {
                if (b == biome) {
                    biomeAllowed = true;
                    break;
                }
            }
            if (!biomeAllowed) return false;
        }
        return true;
    }

    @Override
    public void populate(TerraformWorld tw, PopulatorDataAbstract data) {
        // Vanilla structures are generated by the NMS ChunkGenerator during generation, not here.
    }

    @Override
    public @NotNull Random getHashedRandom(@NotNull TerraformWorld tw, int chunkX, int chunkZ) {
        return tw.getHashedRand(seedModifier, chunkX, chunkZ);
    }

    @Override
    public boolean isEnabled() {
        return enabled;
    }
}
